import { Project, Service, Client } from '@/types'

export const projects: Project[] = [
  {
    id: '1',
    title: 'Diseño estructural – Goodyear Almacén',
    client: 'Goodyear',
    category: 'Ingeniería Estructural',
    description: 'Diseño y cálculo estructural completo para nuevo almacén industrial de 2,500 m².',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop',
    year: '2024',
    featured: true,
  },
  {
    id: '2',
    title: 'Trinchera para prensas de vulcanización',
    client: 'Lima Caucho',
    category: 'Obras Civiles',
    description: 'Construcción de trinchera especializada para sistema de prensas de vulcanización.',
    image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=600&fit=crop',
    year: '2024',
    featured: true,
  },
  {
    id: '3',
    title: 'Montaje de tanque pulmón de aire',
    client: 'Ransa',
    category: 'Montaje Industrial',
    description: 'Instalación completa de tanque pulmón con capacidad de 15,000 litros.',
    image: 'https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&h=600&fit=crop',
    year: '2023',
    featured: true,
  },
  {
    id: '4',
    title: 'Instalación de tubería de vapor y condensado',
    client: 'San Fernando',
    category: 'Piping',
    description: 'Sistema completo de tubería de vapor de alta presión y retorno de condensado.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
    year: '2024',
    featured: false,
  },
  {
    id: '5',
    title: 'Fabricación de tolva y rampa acero inoxidable',
    client: 'Backus',
    category: 'Estructuras Metálicas',
    description: 'Fabricación e instalación de tolva industrial en acero inoxidable 304.',
    image: 'https://images.unsplash.com/photo-1567789884554-0b844b597180?w=800&h=600&fit=crop',
    year: '2023',
    featured: true,
  },
  {
    id: '6',
    title: 'Señalización industrial FAMESA',
    client: 'FAMESA',
    category: 'Señalización',
    description: 'Sistema completo de señalización industrial según normativa de seguridad.',
    image: 'https://images.unsplash.com/photo-1590959651373-a3db0f38a961?w=800&h=600&fit=crop',
    year: '2024',
    featured: false,
  },
  {
    id: '7',
    title: 'Estructuras metálicas Pieriplast',
    client: 'Pieriplast',
    category: 'Estructuras Metálicas',
    description: 'Fabricación y montaje de estructuras metálicas para ampliación de planta.',
    image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&h=600&fit=crop',
    year: '2024',
    featured: true,
  },
  {
    id: '8',
    title: 'Techo estructural prensa Frenosa',
    client: 'Frenosa',
    category: 'Estructuras Metálicas',
    description: 'Diseño y construcción de techo estructural para área de prensas.',
    image: 'https://images.unsplash.com/photo-1485083269755-a7b559a4fe5e?w=800&h=600&fit=crop',
    year: '2023',
    featured: false,
  },
  {
    id: '9',
    title: 'Remodelación de oficinas',
    client: 'Mexichem',
    category: 'Obras Civiles',
    description: 'Remodelación integral de oficinas administrativas con diseño moderno.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop',
    year: '2024',
    featured: false,
  },
  {
    id: '10',
    title: 'Desmontaje de prensas 80TN – Lima Caucho',
    client: 'Lima Caucho',
    category: 'Montaje Industrial',
    description: 'Desmontaje técnico especializado de prensas de 80 toneladas.',
    image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebb6122?w=800&h=600&fit=crop',
    year: '2024',
    featured: true,
  },
  {
    id: '11',
    title: 'Montaje piping — varios clientes',
    client: 'Varios',
    category: 'Piping',
    description: 'Proyectos de montaje de tuberías industriales para múltiples clientes.',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&h=600&fit=crop',
    year: '2024',
    featured: false,
  },
  {
    id: '12',
    title: 'Base metálica para balanzas de camiones',
    client: 'Forus',
    category: 'Estructuras Metálicas',
    description: 'Fabricación de base estructural para sistema de pesaje de vehículos.',
    image: 'https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=800&h=600&fit=crop',
    year: '2023',
    featured: false,
  },
]

export const services: Service[] = [
  {
    id: '1',
    title: 'Estructuras Metálicas',
    description: 'Diseño, fabricación y montaje de estructuras metálicas para naves industriales, almacenes y edificaciones comerciales.',
    icon: 'building',
    features: ['Diseño estructural', 'Fabricación en planta', 'Montaje especializado', 'Certificación de calidad'],
  },
  {
    id: '2',
    title: 'Piping Industrial',
    description: 'Sistemas completos de tuberías para transporte de fluidos, vapor, gases y productos químicos.',
    icon: 'pipe',
    features: ['Tuberías de proceso', 'Vapor y condensado', 'Sistemas de refrigeración', 'Pruebas hidrostáticas'],
  },
  {
    id: '3',
    title: 'Señalización Industrial',
    description: 'Implementación de sistemas de señalización según normativas de seguridad industrial.',
    icon: 'alert-triangle',
    features: ['Señales de seguridad', 'Demarcación de áreas', 'Señalización vial', 'Normativa OSHA'],
  },
  {
    id: '4',
    title: 'Obras Civiles',
    description: 'Construcción y remodelación de infraestructura civil para instalaciones industriales.',
    icon: 'hard-hat',
    features: ['Cimentaciones', 'Pisos industriales', 'Trincheras', 'Remodelaciones'],
  },
  {
    id: '5',
    title: 'Montaje Industrial',
    description: 'Montaje y desmontaje de equipos industriales, maquinaria y líneas de producción.',
    icon: 'cog',
    features: ['Montaje de equipos', 'Alineamiento', 'Izaje especializado', 'Desmontaje técnico'],
  },
  {
    id: '6',
    title: 'Tanques y Tuberías',
    description: 'Fabricación e instalación de tanques de almacenamiento y sistemas de tuberías especializados.',
    icon: 'cylinder',
    features: ['Tanques atmosféricos', 'Recipientes a presión', 'Tuberías especiales', 'Recubrimientos'],
  },
  {
    id: '7',
    title: 'Mantenimiento Industrial',
    description: 'Servicios de mantenimiento preventivo y correctivo para instalaciones industriales.',
    icon: 'wrench',
    features: ['Mantenimiento preventivo', 'Reparaciones', 'Paradas de planta', 'Emergencias 24/7'],
  },
  {
    id: '8',
    title: 'Ingeniería Estructural',
    description: 'Servicios de diseño y cálculo estructural para proyectos industriales y comerciales.',
    icon: 'drafting-compass',
    features: ['Cálculo estructural', 'Planos de fabricación', 'Memorias de cálculo', 'Supervisión técnica'],
  },
]

export const clients: Client[] = [
  { id: '1', name: 'Goodyear', logo: '/clients/goodyear.svg' },
  { id: '2', name: 'Lima Caucho', logo: '/clients/lima-caucho.svg' },
  { id: '3', name: 'Ransa', logo: '/clients/ransa.svg' },
  { id: '4', name: 'Frenosa', logo: '/clients/frenosa.svg' },
  { id: '5', name: 'FAMESA', logo: '/clients/famesa.svg' },
  { id: '6', name: 'San Fernando', logo: '/clients/san-fernando.svg' },
  { id: '7', name: 'Forus', logo: '/clients/forus.svg' },
  { id: '8', name: 'Mexichem', logo: '/clients/mexichem.svg' },
  { id: '9', name: 'Backus', logo: '/clients/backus.svg' },
  { id: '10', name: 'Pieriplast', logo: '/clients/pieriplast.svg' },
]

export const companyInfo = {
  name: 'SOLUCIONES INTEGRALES JS S.A.C.',
  tagline: 'Ingeniería Industrial de Excelencia',
  description: 'Empresa peruana especializada en servicios de ingeniería, proyectos civiles, estructuras metálicas, piping, montaje industrial y mantenimiento. Más de 15 años de experiencia brindando soluciones integrales a la industria.',
  phone: '+51 999 999 999',
  email: 'contacto@solucionesintegralesjs.com',
  address: 'Lima, Perú',
  ruc: '20123456789',
  socialMedia: {
    linkedin: 'https://linkedin.com/company/soluciones-integrales-js',
    facebook: 'https://facebook.com/solucionesintegralesjs',
    instagram: 'https://instagram.com/solucionesintegralesjs',
  },
}
